# -*- coding: utf-8 -*-
"""atividade_pratica01.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJ2xvjEs5_WVeWZNMxfNgdnY9tx-dRLc
"""

1
print ("===  Calculadora de Frete ===")
kg = float(input("Informe o peso da encomenda:KG "))
print ("Informe qual região você mora? ")
print ("1- Região Nordeste")
print ("2- Região Sudeste")
print ("3- Região Sul")
opcao = int(input("Escolha a opção: "))
match opcao:
    case 1:
        print ("O frete será GRATUITO")
    case 2:
        print ("O valor calculado terá um  acréscimo de 10%")
        if kg <= 1:
            total = 10.00
        elif kg > 1 and kg <= 5:
            total = 20.00
        elif kg > 5 and kg <= 10:
            total = 35.00
        else:
            total = 50.00
        acrescimo = 0.10 * total
        total = total + acrescimo
        print (f"O valor total do frete será de {total:.2f}")
    case 3:
        print ("O valor calculado terá um  acréscimo de 15%")
        if kg <= 1:
            total = 10.00
        elif kg > 1 and kg <= 5:
            total = 20.00
        elif kg > 5 and kg <= 10:
            total = 35.00
        else:
            total = 50.00
        acrescimo = 0.15 * total
        total = total + acrescimo
        print (f"O valor total do frete será de {total:.2f}")
    case _:
        print ("Opção inválida!")