# -*- coding: utf-8 -*-
"""exercicio_aula02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRheSgvJc6H1-ODcytHcZsh0LOp4x2M3
"""

print ("Escolha qual Grandezas Elétricas quer calcular: ")
print ("1- Tensão(U)")
print ("2- Corrente(I)")
print ("3- Resistência(R)")
opcao = int (input("Escolha qual opção: "))
match opcao:
  case 1:
    print ("=== FÓRMULA DE TENSÃO ===")
    print ("U = R x I")
    r = float(input("Informe o valor da Resitência(R): "))
    i = float(input("Informe o valor da Corrente(I): "))
    print (f"O valor da Tensão é de {r * i} volts")
    print ("----------------------------------------------")
  case 2:
    print ("=== FÓRMULA DE CORRENTE ===")
    print ("I = U / R")
    u = float(input("Informe o valor da Tensão(U): "))
    r = float(input("Informe o valor da Resistência(R): "))
    if r == 0:
      print ("Não é possível realizar o cálculo")
    else:
      print (f"O valor da Corrente é de {u / r} Amperes")
  case 3:
    print ("=== FÓRMULA DE RESITÊNCIA ===")
    print ("R = U / I")
    u = float(input("Informe o valor da Tensão(U): "))
    i = float(input("Informe o valor da Corrente(I): "))
    if i == 0:
      print ("Não é possível realizar o cálculo")
    else:
      print (f"O valor da Resitência é de {u / i} Ohms")
  case _:
    print ("Opção inválida")