# -*- coding: utf-8 -*-
"""exercicio_aula01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cESC8vYMpegJu717RfMZbNL6j6B0d9B3
"""

nome = input ("Escreva seu nome: ")
idade = int (input("Escreva sua idade: "))
peso = float(input ("Escreva seu peso: "))
altura = float (input ("Escreva seu altura: "))
horas_dorme = float (input ("Escreva quantas horas você dorme por dia: "))
horas_celular = float (input ("Escreva quantas horas você usa o celular por dia: "))

#dias vividos
dias = idade * 365
#horas vividas
horas = dias * 24
#minutos vividos
minutos = dias * 1440
#imc
imc = peso / (altura ** 2)
#horas dormidas na vida
sono = horas_dorme * dias
#dias inteiros dormindo
dias_dormindo = (horas_dorme * 365) / 24
#tempo de tela
dias_celular = (horas_celular * 365) / 24
print ("---------------------------\n")
print (f"Dias vividos: {dias}")
print (f"Horas vividas: {horas}")
print (f"Minutos vividos: {minutos}")
print (f"IMC: {imc : .2f}")
print (f"Horas dormidas na vida: {sono : .0f}")
print (f"Dias inteiros dormindo no ultimo ano: {dias_dormindo : .2f}")
print (f"Dias inteiros dormindo usando o celular no ultimo ano: {dias_celular : .2f}")